### ISSUE TITLE
plane by plane segmentation or full 3D?

### ISSUE THREAD

**Issue by memphizz** [neurobiology-ut/PHILOW#33]
I see 2D convolutions are used in the model, does the code do plane-by-plane segmentation?

**Comment by Shogosuga** [comment]
Yes the prediction per se is done in 2D. We newly implemented TAP method, which facilitates quite accurate 3D prediction using 2D training datasets. Please see the paper on [bioRxiv](https://www.biorxiv.org/content/10.1101/2021.06.11.448083v1) for details.

**Comment by memphizz** [comment]
Thanks for the response. I am interested to use the tool for segmenting large 2D RGB images. Is it possible?

**Comment by Shogosuga** [comment]
Thanks for considering using PHILOW.
This application does not currently support RGB images. Please wait a little longer, as we plan to support the segmentation of RGB images in the next update.
